version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --default-authentication-plugin=mysql_native_password
    environment:
      TZ:  "/usr/share/zoneinfo/Asia/Tokyo"
      MYSQL_DATABASE: healthrecord_development
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
volumes:
  mysql-db:
    driver: local
